"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";
import { atomRootStore } from "@src/app-state/atom-setup";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AuthRoutes } from "./layout/auth-layout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={atomRootStore}>
          <AntdRegistry>
            <AuthRoutes>{children}</AuthRoutes>
          </AntdRegistry>
        </Provider>
      </body>
    </html>
  );
}
